### PR TITLE
Add confirmation dialog when quitting

### PR DESCRIPTION
**Pull request by SimonAlling**
In the original MS-DOS game, when Escape is pressed between rounds, the game immediately exits to the splash screen. In 83ca2595037f462f6467d196d15ae146aaeec5b9, the legacy JavaScript version introduced an optional confirmation dialog (enabled by default), because accidentally quitting in the middle of a game _sucks_. Unlike in the original game, "quitting" in the legacy JavaScript version means going to the lobby, not the splash screen, because that's almost always more useful.

This PR brings a similar confirmation dialog to the Elm version. Since we don't have any user-facing preferences (yet), it's always enabled.

Having experimented with various approaches, I've decided to go with this one, which implements keyboard interaction entirely in Elm, instead of relying on the browser's native behavior.

Neither solution is without its flaws. The browser approach has these disadvantages:

  * The arrow keys don't work for moving focus between the buttons.
  * Pressing Tab (or Shift + Tab) cycles through _all focusable elements_ in the page, and even the browser chrome, so the dialog doesn't feel modal.
  * When the dialog is opened, the "No" button must be focused with `Browser.Dom.focus` and `Task.attempt`. That is, we must look it up by ID and handle the possibility that it doesn't exist, even though we know that it does.
  * We have to control in Elm whether we should call the `preventDefault` method in JavaScript or not (for example by conditionally setting an attribute in Elm and check for it in JavaScript).

The Elm approach has these:

  * We're reinventing the wheel when it comes to moving focus between input elements and interacting with them.
  * Supporting more than two input elements would require a more general implementation for the complexity to stay reasonable.
  * Since we use `event.code` (the physical key), not `event.key` (the meaning of the key), the dialog may not behave as expected with non-QWERTY layouts.

While we suspect that the Elm approach may not cut it if/when we introduce more input elements down the road, I think this implementation is good enough for now. I also believe there's value in documenting in the Git history that we initially did it this way and why.

I decided to go with `<div>` rather than `<dialog>` because [the latter isn't supported in relatively new versions of Firefox (97) and Safari (15.3)](https://caniuse.com/dialog).

💡 `git show --color-words='goToLobby .+|\w+|.' --ignore-space-change`

### CODE REVIEW

**Comment by SimonAlling** [comment]
I'm _really_ not sure that this is a good way to implement a dialog, so I would like @lydell's opinion about the general idea before spending time on the details.

  * Should we handle key presses, which button is selected right now, etc, or can we just let the browser deal with all of that in some sensible way?
  * Does it make sense to use `event.code` to determine what navigation action the user intended to take in the dialog?

It must be possible to click on the buttons as well as use the L/R arrow keys (and possibly U/D) and Enter/Space to interact with the dialog.

I recommend `git diff --ignore-space-change`.

**Comment by SimonAlling** [comment]
@lydell:

> Mitt första försök skulle vara att använda webbläsaren så mycket som möjligt. Två `<button>`. Den som är vald är stylad med `:focus`. Tab, shift+tab, enter, space får du gratis. Du kan lyssna på vänster- och högerpiltryck och använda https://elm.dmy.fr/packages/elm/browser/latest/Browser-Dom#focus för att flytta fokus. Edit: Fast hur vet man då vart fokus ska flyttas? En annan grej: Med ditt sätt är en knapp garanterad att se fokuserad ut. Med webbläsar-native kan det bli att ingen av dem är fokuserad.
>
> Jag tänker att man vill använda key och inte code här, för att det är tangenternas ”mening” och inte position på det fysiska tangentbordet vi är ute efter. Så om nån ändrat sin tangentbordslayout så borde det följas.

Summary:

> I'd try to rely on the browser's native behavior as much as possible. You can use `Browser.Dom.focus` for the arrow keys.
>
> I believe we want `key` rather than `code` because we're interested in the "meaning" of the key, not its physical position.

I've actually given it a try with `Task` and `Browser.Dom.focus`. One issue that seems to arise then is that we call `preventDefault` all `keydown` events, so the keyboard doesn't work at all for interacting with the dialog, unless we toggle the default-behavior prevention via a port based on whether the dialog is open or not. Or maybe we can whitelist certain keys?

We might ask ourselves to what degree we want this to be an Elm game vs a web app. Like, how tightly coupled to the web platform do we want to be? Maybe we've already made that decision by choosing Elm in the first place?

Regarding `.key` vs `.code`, that question is only relevant if we go for the "all-Elm" approach, and then I'm strongly in favor of `.key`.

**Comment by SimonAlling** [comment]
The reason I haven't just merged this is that I believe a future settings GUI should be implemented in the same way as this dialog. An arbitrary number of ordered, focusable inputs is easy enough to support, but I was almost immediately taken aback by the fact that _holding_ Tab doesn't work as it usually does. There are probably more such quirks that one may not think about until one encounters them, and reinventing the wheel simply isn't very tempting.

**Comment by lydell** [comment]
A settings GUI probably will have text inputs at some point, won’t it? Then we pretty much _have_ to turn off the `preventDefault` of all keydown events and rely on the browser. Ideas for toggling the `preventDefault`:

- Ports. Risk: Might end up in a buggy state where we `preventDefault` in the settings GUI, but not in the game.
- HTML attribute. `if (someNode.hasAttribute("data-prevent-default-keydown")) { event.preventDefault() }`. This might be safer since the `view` is always up-to-date with the `Model` without us having to do anything. But maybe it feels like an “ugly” solution?

**Comment by SimonAlling** [comment]
> A settings GUI probably will have text inputs at some point, won’t it? Then we pretty much _have_ to turn off the `preventDefault` of all keydown events and rely on the browser.

Yes! And it feels like we'll just make everything very difficult for ourselves in general if we're going to re-implement standard browser behavior in a settings form with many different kinds of inputs etc.

> Ports. Risk: Might end up in a buggy state where we `preventDefault` in the settings GUI, but not in the game, if we forget to call a port in some place.

Yeah. That solution spontaneously doesn't appeal to me because it feels overly imperative.

> HTML attribute. `if (someNode.hasAttribute("data-prevent-default-keydown")) { event.preventDefault() }`. This might be safer since the `view` is always up-to-date with the `Model` without us having to do anything. But maybe it feels like an “ugly” solution?

Actually it doesn't feel ugly to me at all. Really feels like we can *write what we mean*™: "when the app state is 𝑥, then the key-event handling is 𝑦".

**Comment by SimonAlling** [comment]
I'm considering merging this for two reasons:

* I like how it works (arrow keys for example).
* There is value in having this solution stored in the Git history, even if we decide to replace it down the road.

**Pull request merged**
